colour: '#999999'
cross_section: 0.2158
histogram: VVV
label: VVV
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/WWW_4F_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1_MCUL2017_HToSS/231106_094112
mc: true
name: WWW
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/VVV/WWW/
sum_weights: 36869.161605946836
total_events: 171000
