colour: '#999999'
cross_section: 0.1707
histogram: VVV
label: VVV
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/WWZ_4F_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1_MCUL2017_HToSS/231106_095535
mc: true
name: WWZ
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/VVV/WWZ/
sum_weights: 30386.29170925995
total_events: 178000
