colour: '#999999'
cross_section: 0.05709
histogram: VVV
label: VVV
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/WZZ_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1_MCUL2017_HToSS/231106_105457
mc: true
name: WZZ
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/VVV/WZZ/
sum_weights: 17023.649914249567
total_events: 298000
