cuts: "configs/2017/cuts/SRCuts.yaml"
plots: "configs/plots/plotDileptonConf.yaml"
outputFolder: "plots/2017/mumu/"
outputPostfix: "mumu"
channelName: "mumu"
datasets:
# ggH
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p4_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p4_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p4_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p4_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p6_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p6_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p6_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p6_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p8_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p8_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p8_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p8_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p9_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p9_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p9_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS0p9_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p1_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p1_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p1_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p1_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p2_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p2_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p2_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p2_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p4_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p4_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p4_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p4_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p6_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p6_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p6_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p6_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p8_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p8_ctauS1.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p8_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS1p8_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS2_ctauS0.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS2_ctauS100.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS2_ctauS10.yaml"
 - "configs/2017/datasets/ggH/HToSS_MH125_MS2_ctauS1.yaml"
