cuts: "configs/2017/cuts/SRCuts.yaml"
plots: "configs/plots/plotDileptonConf.yaml"
outputFolder: "plots/2017/mumu/"
outputPostfix: "mumu"
channelName: "mumu"
datasets:
# QCD
 - "configs/2017/datasets/QCD/QCD_Pt-15to20_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-20to30_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-20to30_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-30to50_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-50to80_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-80to120_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-120to170_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-170to300_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-300to470_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-470to600_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-600to800_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-800to1000_MuEnrichedPt5.yaml"
 - "configs/2017/datasets/QCD/QCD_Pt-1000toInf_MuEnrichedPt5.yaml"
# # Z+jets
#  - "configs/2017/datasets/DYJetsToLL_Pt/DYJetsToLL_Pt-0To50.yaml"
#  - "configs/2017/datasets/DYJetsToLL_Pt/DYJetsToLL_Pt-50To100.yaml"
#  - "configs/2017/datasets/DYJetsToLL_Pt/DYJetsToLL_Pt-100To250.yaml"
#  - "configs/2017/datasets/DYJetsToLL_Pt/DYJetsToLL_Pt-250To400.yaml"
#  - "configs/2017/datasets/DYJetsToLL_Pt/DYJetsToLL_Pt-400To650.yaml"
#  - "configs/2017/datasets/DYJetsToLL_Pt/DYJetsToLL_Pt-650ToInf.yaml"
# ttbar
 - "configs/2017/datasets/ttbar/ttbar_2l2nu.yaml"
 - "configs/2017/datasets/ttbar/ttbar_hadronic.yaml"
 - "configs/2017/datasets/ttbar/ttbar_semileptonic.yaml"
# # VV
#  - "configs/2017/datasets/VV/WW_2l2nu.yaml"
#  - "configs/2017/datasets/VV/WW_lnu2q.yaml"
#  - "configs/2017/datasets/VV/WZ_2l2q.yaml"
#  - "configs/2017/datasets/VV/WZ_3lnu.yaml"
# #  - "configs/2017/datasets/VV/WZ_lnu2q.yaml"
# #  - "configs/2017/datasets/VV/WZ_l3nu.yaml"
#  - "configs/2017/datasets/VV/ZZ_2l2nu.yaml"
#  - "configs/2017/datasets/VV/ZZ_2l2q.yaml"
#  - "configs/2017/datasets/VV/ZZ_4l.yaml"
#  - "configs/2017/datasets/VV/WG_lnug.yaml"
#  - "configs/2017/datasets/VV/ZG_llg.yaml"
# # Single top
#  - "configs/2017/datasets/singleTop/tHq.yaml"
#  - "configs/2017/datasets/singleTop/t_s_channel.yaml"
#  - "configs/2017/datasets/singleTop/t_t_channel.yaml"
#  - "configs/2017/datasets/singleTop/tbar_t_channel.yaml"
#  - "configs/2017/datasets/singleTop/tW.yaml"
#  - "configs/2017/datasets/singleTop/tbarW.yaml"
#  - "configs/2017/datasets/singleTop/tWZ.yaml"
#  - "configs/2017/datasets/singleTop/tZq.yaml"
# W+jets
#  - "configs/2017/datasets/wPlusJets/wPlusJets.yaml"
# ttV
# #  - "configs/2017/datasets/ttV/ttWTolnu.yaml"
#  - "configs/2017/datasets/ttV/ttW2q.yaml"
#  - "configs/2017/datasets/ttV/ttZToll.yaml"
#  - "configs/2017/datasets/ttV/ttZ2q.yaml"
#  - "configs/2017/datasets/ttV/ttH_bb.yaml"
#  - "configs/2017/datasets/ttV/ttH_nonbb.yaml"
#  - "configs/2017/datasets/ttV/ttgamma.yaml"
# # VVV
#  - "configs/2017/datasets/VVV/WWW.yaml"
#  - "configs/2017/datasets/VVV/WWZ.yaml"
#  - "configs/2017/datasets/VVV/WZZ.yaml"
#  - "configs/2017/datasets/VVV/ZZZ.yaml"
