colour: '#fc0303'
cross_section: 0.017089114000000002
histogram: HToSS_MH125_MS1p4_ctauS100
label: H#rightarrowaa m_{a}=1.4 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS1p4_ctauS100_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedKaon/240227_215851
mc: true
name: HToSS_MH125_MS1p4_ctauS100
plot_type: l
sum_weights: 813601.6932000834
total_events: -1
