colour: '#fc0303'
cross_section: 0.027886338
histogram: HToSS_MH125_MS0p6_ctauS1
label: H#rightarrowaa m_{a}=0.6 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS0p6_ctauS1_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedPion/240710_232202
mc: true
name: HToSS_MH125_MS0p6_ctauS1
plot_type: l
sum_weights: 899593.338600159
total_events: -1
