colour: '#fc0303'
cross_section: 0.04072082
histogram: HToSS_MH125_MS2_ctauS0
label: H#rightarrowaa m_{a}=2 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS2_ctauS0_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedKaon/231004_185438
mc: true
name: HToSS_MH125_MS2_ctauS0
plot_type: l
skim_location: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/dummy/
sum_weights: 393632.5032000114
total_events: -1
