colour: '#fc0303'
cross_section: 0.0138596828
histogram: HToSS_MH125_MS1p2_ctauS100
label: H#rightarrowaa m_{a}=1.2 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS1p2_ctauS100_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedKaon/240227_215928
mc: true
name: HToSS_MH125_MS1p2_ctauS100
plot_type: l
sum_weights: 732894.5705996623
total_events: -1
