colour: '#fc0303'
cross_section: 0.0031836720000000002
histogram: HToSS_MH125_MS1_ctauS0
label: H#rightarrowaa m_{a}=1 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS1_ctauS0_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedPion/231114_141709
mc: true
name: HToSS_MH125_MS1_ctauS0
plot_type: l
sum_weights: 676719.6635997919
total_events: -1
