colour: '#fc0303'
cross_section: 0.005977904
histogram: HToSS_MH125_MS1p1_ctauS1
label: H#rightarrowaa m_{a}=1.1 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS1p1_ctauS1_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedKaon/240227_215939
mc: true
name: HToSS_MH125_MS1p1_ctauS0p1
plot_type: l
sum_weights: 312345.372000058
total_events: -1
