colour: '#fc0303'
cross_section: 0.0185889448
histogram: HToSS_MH125_MS0p8_ctauS1
label: H#rightarrowaa m_{a}=0.8 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS0p8_ctauS1_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedPion/240227_220158
mc: true
name: HToSS_MH125_MS0p8_ctauS0p1
plot_type: l
sum_weights: 861097.9529993666
total_events: -1
