colour: '#fc0303'
cross_section: 0.0332177716
histogram: HToSS_MH125_MS1p8_ctauS100
label: H#rightarrowaa m_{a}=1.8 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS1p8_ctauS100_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedKaon/240701_121633
mc: true
name: HToSS_MH125_MS1p8_ctauS100
plot_type: l
sum_weights: 1096216.2539993275
total_events: -1
