colour: '#fc0303'
cross_section: 0.040026643199999996
histogram: HToSS_MH125_MS0p4_ctauS10
label: H#rightarrowaa m_{a}=0.4 c_{#tau}=1
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/HToSSTo2Mu2Hadrons_MH125_MS0p4_ctauS10_TuneCP2_13TeV-powheg-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS_ChargedPion/240227_220319
mc: true
name: HToSS_MH125_MS0p4_ctauS10
plot_type: l
sum_weights: 3233784.2447980656
total_events: -1
