colour: '#ff99cc'
cross_section: 2518000.0
histogram: QCD_20to30
label: QCD_20to30
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-20To30_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS/231016_201916
mc: true
name: QCD_Pt-20to30_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-20to30_MuEnrichedPt5/
sum_weights: 64167783.798831634
total_events: -1
