colour: '#8aefff'
cross_section: 1361000.0
histogram: QCD_30to50
label: QCD_30to50
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-30To50_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v1_MCUL2017_HToSS/231016_203249
mc: true
name: QCD_Pt-30to50_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-30to50_MuEnrichedPt5/
sum_weights: 58990479.0
total_events: -1
