colour: '#999999'
cross_section: 2797000.0
histogram: QCD_15to20
label: QCD_15to20
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-15To20_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231016_200554
mc: true
name: QCD_Pt-15to20_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-15to20_MuEnrichedPt5/
sum_weights: 9021334.990522824
total_events: -1
