colour: '#006699'
cross_section: 1.62
histogram: QCD_1000toInf
label: QCD_1000toInf
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-1000_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231014_181211
mc: true
name: QCD_Pt-1000toInf_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-1000toInf_MuEnrichedPt5/
sum_weights: 27478273.0
total_events: -1
