colour: '#e2f9fd'
cross_section: 3.25
histogram: QCD_800to1000
label: QCD_800to1000
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-800To1000_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAOD-106X_mc2017_realistic_v6-v2_MCUL2017_HToSS/231017_084828
mc: true
name: QCD_Pt-800to1000_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-800to1000_MuEnrichedPt5/
sum_weights: 78171998.0
total_events: -1
