colour: '#10c4e4'
cross_section: 87740.0
histogram: QCD_80to120
label: QCD_80to120
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-80To120_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231016_205942
mc: true
name: QCD_Pt-80to120_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-80to120_MuEnrichedPt5/
sum_weights: 45986550.6851811
total_events: -1
