colour: '#fc0303'
cross_section: 7019.0
histogram: QCD_170to300
label: QCD_170to300
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-170To300_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231017_075428
mc: true
name: QCD_Pt-170to300_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-170to300_MuEnrichedPt5/
sum_weights: 73071987.0
total_events: -1
