colour: '#fde2eb'
cross_section: 18.22
histogram: QCD_600to800
label: QCD_600to800
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-600To800_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231017_083508
mc: true
name: QCD_Pt-600to800_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-600to800_MuEnrichedPt5/
sum_weights: 39321941.14210759
total_events: -1
