colour: '#339933'
cross_section: 622.6
histogram: QCD_300to470
label: QCD_300to470
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-300To470_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231017_080804
mc: true
name: QCD_Pt-300to470_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-300to470_MuEnrichedPt5/
sum_weights: 58692920.280471444
total_events: -1
