colour: '#ffff33'
cross_section: 58.86
histogram: QCD_470to600
label: QCD_470to600
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/QCD_Pt-470To600_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231020_084006
mc: true
name: QCD_Pt-470to600_MuEnrichedPt5
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/QCD/QCD_Pt-470to600_MuEnrichedPt5/
sum_weights: 39491905.05473166
total_events: -1
