executable = /user/yvekemans/MasterThesis/ZHTollSS_analysis/AnalyzeJob.sh
#executable = /user/yvekemans/MasterThesis/ZHTollSS_analysis/WeightsJob.sh

arguments = $(cfg) $(cuts) $(output) $(flow) $(fhigh) $(dataset) $(year)

should_transfer_files = no

error = /user/yvekemans/MasterThesis/ZHTollSS_analysis/error/error_$(dataset)_$(year)_$(flow)-$(fhigh).txt
output = /user/yvekemans/MasterThesis/ZHTollSS_analysis/out/out_$(dataset)_$(year)_$(flow)-$(fhigh).txt
log = /user/yvekemans/MasterThesis/ZHTollSS_analysis/log/log_$(dataset)_$(year)_$(flow)-$(fhigh).txt

#requirements = ((OpSysAndVer =?= "CentOS7"))

#request_cpus=4
#request_memory=10000
#+JobFlavour = "longlunch"
+JobFlavour = "espresso"
max_retries = 5
queue cfg,cuts,output,flow,fhigh,dataset,year from params_signal_kaon_UL2017.txt 
