executable = /user/yvekemans/MasterThesis/ZHTollSS_analysis/HaddJob.sh
arguments = $(out) $(in) $(proc) 

should_transfer_files = no

error = /user/yvekemans/MasterThesis/ZHTollSS_analysis/error/error_$(proc).txt
output = /user/yvekemans/MasterThesis/ZHTollSS_analysis/out/out_$(proc).txt
log = /user/yvekemans/MasterThesis/ZHTollSS_analysis/log/log_$(proc).txt

#request_cpus=4
+JobFlavour = "longlunch"
queue out,in,proc from hadd_params_lv1.txt
