executable = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/AnalyzeJob.sh
#executable = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/WeightsJob.sh

arguments = $(cfg) $(cuts) $(output) $(flow) $(fhigh) $(dataset) $(year)

should_transfer_files = no

error = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/error/error_$(dataset)_$(year)_$(flow)-$(fhigh).txt
output = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/out/out_$(dataset)_$(year)_$(flow)-$(fhigh).txt
log = /user/sdansana/CMSSW_10_6_27/src/HToSS_analysis/log/log_$(dataset)_$(year)_$(flow)-$(fhigh).txt

#requirements = ((OpSysAndVer =?= "CentOS7"))

#request_cpus=4
#request_memory=10000
+JobFlavour = "longlunch"
#+JobFlavour = "espresso"
max_retries = 5
queue cfg,cuts,output,flow,fhigh,dataset,year from params_signal_pion_UL2016_APV.txt 
