colour: '#339933'
cross_section: 0.5269
histogram: ttV
label: t#bar{t}V
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/ttHTobb_M125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231106_134202
mc: true
name: ttH_bb
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/ttV/ttH_bb/
sum_weights: 3919780.9483485376
total_events: 7825000
