colour: '#339933'
cross_section: 0.5638
histogram: ttV
label: t#bar{t}V
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/ttHToNonbb_M125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231102_225006
mc: true
name: ttH_nonbb
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/ttV/ttH_nonbb/
sum_weights: 2540302.943198242
total_events: 5070989
