colour: '#339933'
cross_section: 0.4432
histogram: ttV
label: t#bar{t}V
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1_MCUL2017_HToSS/231102_231847
mc: true
name: ttW_qq
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/ttV/ttW2q/
sum_weights: 444333.9716705027
total_events: 655018
