colour: '#006699'
cross_section: 0.04704
histogram: Zjets
label: Z+jets
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/DYJetsToLL_LHEFilterPtZ-650ToInf_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231030_183523
mc: true
name: DYJetsToLL_Pt-650ToInf
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/DYJetsToLL_Pt/DYJetsToLL_Pt-650ToInf/
sum_weights: 663302.9929131091
