name: "ggH_HToSS_MS1p1_ctauS0_raw"
locations:
    - "/pnfs/iihe/cms/store/user/almorton/MC/skims2017_v5/ggH_noCuts/NLO_ggH_HToSS_SmuonHadronFiltered_M125_MS1p1_ctauS0/"
cross_section: 0.109674208
mc: true
histogram: "ggH_HToSS_MS1p1_ctauS0_raw"
colour: "#fc0303"
label: "H#rightarrowaa m_{a}=1.1 c_{#tau}=0"
plot_type: "l"

