name: "ggH_HToSS_MS1p8_ctauS1_raw"
locations:
    - "/pnfs/iihe/cms/store/user/almorton/MC/skims2017_v5/ggH_noCuts/NLO_ggH_HToSS_SmuonHadronFiltered_M125_MS1p8_ctauS1/"
cross_section: 1.3581102528
mc: true
histogram: "ggH_HToSS_MS1p8_ctauS1_raw"
colour: "#fc0303"
label: "H#rightarrowaa m_{a}=1.8 c_{#tau}=1"
plot_type: "l"

