name: "ggH_HToSS_MS0p8_ctauS100_raw"
locations:
    - "/pnfs/iihe/cms/store/user/almorton/MC/skims2017_v5/ggH_noCuts/NLO_ggH_HToSS_SmuonHadronFiltered_M125_MS0p8_ctauS100/"
cross_section: 0.6307257992
mc: true
histogram: "ggH_HToSS_MS0p8_ctauS100_raw"
colour: "#fc0303"
label: "H#rightarrowaa m_{a}=0.8 c_{#tau}=100"
plot_type: "l"


