name: "ggH_HToSS_MS2_ctauS0"
locations:
    - "/pnfs/iihe/cms/store/user/almorton/MC/skims2017_v5/ggH/NLO_ggH_HToSS_SmuonHadronFiltered_M125_MS2_ctauS0/"
cross_section: 2.9251796028
mc: true
histogram: "ggH_HToSS_MS2_ctauS0"
colour: "#fc0303"
label: "H#rightarrowaa m_{a}=2 c_{#tau}=0"
plot_type: "l"

