colour: '#ff99cc'
cross_section: 69.09
histogram: SingleTop
label: Single top
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1_MCUL2017_HToSS/231030_223632
mc: true
name: tbar_t_channel
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/singleTop/tbar_t_channel/
sum_weights: 4471058880.089036
total_events: 69921000
