colour: '#ff99cc'
cross_section: 32.45
histogram: SingleTop
label: Single top
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231030_212428
mc: true
name: tW
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/singleTop/tW/
sum_weights: 183284888.0073647
total_events: 5649000
