colour: '#ff99cc'
cross_section: 0.01103
histogram: SingleTop
label: Single top
locations:
- /pnfs/iihe/cms/store/user/almorton/MC/skims2017_v4/singleTop/tWz_tWll/
mc: true
name: tWZ
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/singleTop/tWZ/
sum_weights: 86276.0
total_events: -1
