colour: '#ff9933'
cross_section: 51.65
histogram: VV
label: VV
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231106_102436
mc: true
name: WW_lnu2q
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/VV/WW_lnu2q/
sum_weights: 3244407037.8183594
total_events: -1
