colour: '#ff9933'
cross_section: 3.414
histogram: VV
label: VV
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231106_112517
mc: true
name: WZ_l3nu
plot_type: f
sum_weights: 13976291.284531038
total_events: -1
