colour: '#ff9933'
cross_section: 55.48
histogram: VV
label: VV
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/ZGToLLG_01J_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1_MCUL2017_HToSS/231106_120949
mc: true
name: ZG_llg
plot_type: f
sum_weights: 2942151047.990877
total_events: -1
