colour: '#a65628'
cross_section: 1.325
histogram: VV
label: VV
locations: /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/nTuples/ZZTo4L_TuneCP5_13TeV_powheg_pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2_MCUL2017_HToSS/231106_125530
mc: true
name: ZZ_4l
plot_type: f
skim_location:
- /pnfs/iihe/cms/store/user/sdansana/HToSS/MC/postNTupleSkims/2017/VV/ZZ_4l/
sum_weights: 131669254.39417708
total_events: 99388000
