cuts:
  dihadron:
    charge: OS
    dR: 0.4
    flag: true
    pt: 20
    sumptch: 1000.0
    sumptchLeading: 1000.0
  dimuon:
    charge: OS
    dR: 0.4
    flag: true
    pt: 0
    reliso: 100
    relisoLeading: 100
  hadrons:
    eta: 2.4
    flag: true
    id: None
    number: 2
    pt: 5
  muons:
    eta: 2.4
    flag: true
    id: Loose
    number: 2
    pt:
      double: -1
      single: 5
    ptLeading:
      double: -1
      single: 29
  recohiggs:
    flag: true
    massHigh: 127.5
    massLow: 122.5
    region: SR
    sideband: 2.5
  recoscalar:
    flag: false
    higherbound:
    - 0.020128417950532475
    - 1.0322676912746693
    lowerbound:
    - -0.019435206113441062
    - 0.9689663832382576
hadronType: pion
metfilters: true
trig: single
